### ISSUE TITLE
Refresh rate not remembered after quit & relaunch / feature: disable stat logging?

### ISSUE THREAD

**Issue by JayBrown** [rugarciap/Turbo-Boost-Switcher#63] opened 2018-07-24 23:01 UTC
Hi, I'm currently testing Turbo Boost Switcher on my old mid-2010 i7 (Arrandale) MacBook Pro (macOS 10.13.6), and I'll probably go for the Pro version on the new 2018 i9 MBP.

I noticed a little bug, namely that TBS doesn't remember the refresh rate after quit & relaunch. I want to set the rate to 60 seconds, because I already have iStat Menus to deal with system stats. However, TBS always resets to the default 4 seconds. (Preferences getting messed up maybe?)

In this regard, I thought about an additional feature for TBS (free or pro, probably pro), namely the option (simple tick box?) to disable system stat logging completely (CPU load, fan speed, temperature). Possible?

**Comment by JayBrown** [comment] 2018-07-24 23:06
Just checked: the plist key `sensorRefreshTime` stays at "60", but the app (slider) shows "4s", so maybe it's just a display issue. (?)

**Comment by rugarciap** [comment] 2018-07-24 23:08
Thanks! Just reproduced, will fix that in the next version since it's just a minor fix on the refresh rate.

Will consider also the feature request..., thanks!!!

**Comment by rugarciap** [comment] 2018-08-26 17:01
Fixed on 2.7.1. Thanks!

**Closed by rugarciap** 2018-08-26 17:01 UTC
Labels: bug, enhancement
