### ISSUE TITLE
Turbo boost switcher not working in 11.5.1

### ISSUE THREAD

**Issue by slavag** [rugarciap/Turbo-Boost-Switcher#172] opened 2021-09-05 09:01 UTC
Turbo boost switcher not working in 11.5.1,
Disable option never turned into enable.
![image](https://user-images.githubusercontent.com/511540/132121357-b8a5d87a-c48f-4176-8b4d-7b8bcdf986c2.png)

Please advise.
Thanks

**Comment by rugarciap** [comment] 2021-09-05 21:33
Hi,

The app works fine with all macOS versions released so far. This is a duplicate of: https://github.com/rugarciap/Turbo-Boost-Switcher/issues/163  . You can take a look there.., in summary, just reboot.

Best.

**Closed by rugarciap** 2021-09-05 21:33 UTC

**Comment by slavag** [comment] 2021-09-06 06:32
I did reboot, this didn't help

**Comment by slavag** [comment] 2021-09-06 06:41
Please see the video

https://user-images.githubusercontent.com/511540/132171812-e61afcdb-8c84-4d71-855c-67d995ee12b3.mov

Thanks
