### ISSUE TITLE
2016 rMBP w/ TouchBar -- should default to using TouchID

### ISSUE THREAD

**Issue by kmishra9** [rugarciap/Turbo-Boost-Switcher#28] opened 2017-01-14 01:20 UTC
Hey there,

Quick issue I came across,

When Turbo Boost Switcher asks for a password, it's possible to use TouchID to enable (a really nice addition which makes the process super smooth and doesn't force me to type my password at all while logging in). This _is possible_ but the issue is TBS asks me for my password, I have to click cancel once, and then it asks me again using TouchID. Typically if it's not the first time and I'm switching back and forth between on and off modes, it asks for TouchID on all subsequent prompts after that first time entering in the password.

If possible, can we have that first prompt ask for the fingerprint?

**Comment by kmishra9** [comment] 2017-07-31 22:54
Just bumping this

**Comment by rugarciap** [comment] 2018-03-05 21:40
I'm going to close this issue as a duplicate of #49.

Best!

**Closed by rugarciap** 2018-03-05 21:40 UTC
Labels: duplicate, enhancement
